baseURL = 'https://clever-kitten-e33e53.netlify.app/'
languageCode = 'sv-sv'
defaultContentLanguage = 'sv'


[params]
  title = 'Turf Västerbotten - bara en zon till'
  metaDescription = "Turf Västerbotten - föreningen för turfare i Västerbotten"


# Languages
[Languages.sv]
languageName = "sv"
languageCode = "sv-sv"
contentDir = "content/sv"
weight = 1
mark = "SV"

[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/en"
weight = 2
mark = "EN"

# [Languages.fr]
# languageName = "fr"
#languageCode = "fr-fr"
# contentDir = "content/fr"
# weight = 3
# mark = "FR"


[taxonomies]
  category= "theme"
  scene = "scenes"
